### ISSUE TITLE
Server Mod Error

### ISSUE THREAD

**Issue by Rakarth802** [glowing-octo-minecraft/issue-tracking#8]
This same error is occurring for these mods: Factorization, Hardcore Ender Expansion, and Open Blocks. This occurs on server start up.

---- Minecraft Crash Report ----
// Why did you do that?

Time: 9/22/14 9:53 AM
Description: Exception in server tick loop

java.lang.NullPointerException: Exception in server tick loop
    at net.minecraft.item.crafting.FurnaceRecipes.func_151397_a(FurnaceRecipes.java:100)
    at net.minecraft.item.crafting.FurnaceRecipes.func_151398_b(FurnaceRecipes.java:125)
    at chylex.hee.mechanics.orb.OrbAcquirableItems.initialize(OrbAcquirableItems.java:31)
    at chylex.hee.HardcoreEnderExpansion.onInit(HardcoreEnderExpansion.java:325)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:513)
    at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:208)
    at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:187)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:118)
    at cpw.mods.fml.common.Loader.initializeMods(Loader.java:691)
    at cpw.mods.fml.server.FMLServerHandler.finishServerLoading(FMLServerHandler.java:97)
    at cpw.mods.fml.common.FMLCommonHandler.onServerStarted(FMLCommonHandler.java:319)
    at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:210)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:387)
    at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- System Details --
Details:
    Minecraft Version: 1.7.10
    Operating System: Windows 7 (amd64) version 6.1
    Java Version: 1.7.0_67, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 457788792 bytes (436 MB) / 1081122816 bytes (1031 MB) up to 8334934016 bytes (7948 MB)
    JVM Flags: 8 total; -Xmx4G -XX:PermSize=256m -XX:MaxPermSize=512m -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn512M -Xmx8000M
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    FML: MCP v9.05 FML v7.10.84.1217 Minecraft Forge 10.13.1.1217 162 mods loaded, 162 mods active
    mcp{9.05} [Minecraft Coder Pack](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized
    FML{7.10.84.1217} [Forge Mod Loader](ForgeMod.jar) Unloaded->Constructed->Pre-initialized->Initialized
    Forge{10.13.1.1217} [Minecraft Forge](ForgeMod.jar) Unloaded->Constructed->Pre-initialized->Initialized
    appliedenergistics2-core{rv1-beta-37} [AppliedEnergistics2 Core](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized
    CodeChickenCore{1.0.3.26} [CodeChicken Core](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized
    <CoFH ASM>{000} [CoFH ASM Data Initialization](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized
    FEPreLoader{1.3.1-beta1} [Forge Essentials|PreLoader](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized
    ImmibisMicroblocks{59.0.3} [Immibis's Microblocks](immibis-microblocks-59.0.3.jar) Unloaded->Constructed->Pre-initialized->Initialized
    Micdoodlecore{} [Micdoodle8 Core](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized
    MobiusCore{1.2.3} [MobiusCore](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized
    NotEnoughItems{1.0.3.56} [Not Enough Items](NotEnoughItems-1.7.10-1.0.3.56-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized
    OpenEye{0.6} [OpenEye](OpenEye-0.6-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized
    ThaumicTinkerer-preloader{0.1} [Thaumic Tinkerer Core](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized
    OpenModsCore{@VERSION@} [OpenModsCore](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized
    FamiliarsAPI{1.7.10} [Familiars API](FamiliarsAPI-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized
    advancedgenetics{1.5.7} [Advanced Genetics](advancedgenetics-1.7.10-1.5.7.jar) Unloaded->Constructed->Pre-initialized->Initialized
    appliedenergistics2{rv1-beta-37} [Applied Energistics 2](appliedenergistics2-rv1-beta-37.jar) Unloaded->Constructed->Pre-initialized->Initialized
    Waila{1.5.4a} [Waila](Waila-1.5.4a_1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized
    ae2tech{1.0-b81} [AE2 Tech Add-On](AE2TechAddOn-1.7.10-1.0-b81-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized
    AetherCraft{1.4.5.68} [AetherCraft](AetherCraft-1.7.10-1.4.5.68.jar) Unloaded->Constructed->Pre-initialized->Initialized
    CoFHCore{1.7.10R3.0.0B6} [CoFH Core](CoFHCore-[1.7.10]3.0.0B6-32.jar) Unloaded->Constructed->Pre-initialized->Initialized
    EE3{0.2.328} [Equivalent Exchange 3](EquivalentExchange3-1.7.10-0.2.328.jar) Unloaded->Constructed->Pre-initialized->Initialized
    Mantle{1.7.10-0.3.1.jenkins180} [Mantle](Mantle-mc1.7.10-0.3.1.jar) Unloaded->Constructed->Pre-initialized->Initialized
    Natura{2.2.0} [Natura](natura-1.7.10-2.2.0-b1.jar) Unloaded->Constructed->Pre-initialized->Initialized
    BiomesOPlenty{2.1.0} [Biomes O' Plenty](BiomesOPlenty-1.7.10-2.1.0.991-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized
    BuildCraft|Core{6.0.17} [BuildCraft](buildcraft-6.0.17.jar) Unloaded->Constructed->Pre-initialized->Initialized
    Forestry{3.0.0.172} [Forestry for Minecraft](forestry_1.7.10-3.0.0.172.jar) Unloaded->Constructed->Pre-initialized->Initialized
    MineFactoryReloaded{1.7.10R2.8.0RC3} [MineFactory Reloaded](MineFactoryReloaded-[1.7.10]2.8.0RC3-591.jar) Unloaded->Constructed->Pre-initialized->Initialized
    Baubles{1.0.1.7} [Baubles](Baubles-1.7.10-1.0.1.7.jar) Unloaded->Constructed->Pre-initialized->Initialized
    Thaumcraft{4.2.0.1} [Thaumcraft](Thaumcraft-1.7.10-4.2.0.1.jar) Unloaded->Constructed->Pre-initialized->Initialized
    Artifice{1.7.10R1.1.4} [Artifice](Artifice-1.7-1.1.4-296.jar) Unloaded->Constructed->Pre-initialized->Initialized
    asielib{0.2.7} [asielib](AsieLib-1.7.10.zip) Unloaded->Constructed->Pre-initialized->Initialized
    Automagy{0.10.2} [Automagy](Automagy-1.7.10-0.10.2.jar) Unloaded->Constructed->Pre-initialized->Initialized
    bdlib{1.4.4.22} [BD Lib](bdlib-mc1710-1.4.4.22.jar) Unloaded->Constructed->Pre-initialized->Initialized
    BiblioCraft{1.8.1} [BiblioCraft](BiblioCraft[v1.8.1][MC1.7.10].jar) Unloaded->Constructed->Pre-initialized->Initialized
    BiblioWoodsBoP{1.8} [BiblioWoods Biomes O'Plenty Edition](BiblioWoods[BiomesOPlenty][v1.8].jar) Unloaded->Constructed->Pre-initialized->Initialized
    BiblioWoodsForestry{1.6} [BiblioWoods Forestry Edition](BiblioWoods[Forestry][v1.6].jar) Unloaded->Constructed->Pre-initialized->Initialized
    BiblioWoodsNatura{1.4} [BiblioWoods Natura Edition](BiblioWoods[Natura][v1.4].jar) Unloaded->Constructed->Pre-initialized->Initialized
    ThermalFoundation{1.7.10R1.0.0B3} [Thermal Foundation](ThermalFoundation-[1.7.10]1.0.0B3-8.jar) Unloaded->Constructed->Pre-initialized->Initialized
    ThermalExpansion{1.7.10R4.0.0B5} [Thermal Expansion](ThermalExpansion-[1.7.10]4.0.0B5-13.jar) Unloaded->Constructed->Pre-initialized->Initialized
    BigReactors{0.4.0rc8} [Big Reactors](BigReactors-0.4.0rc8.jar) Unloaded->Constructed->Pre-initialized->Initialized
    AWWayofTime{v1.0.1g} [Blood Magic: Alchemical Wizardry](Blood Magic-v1.1.0%281.7.10%29.jar) Unloaded->Constructed->Pre-initialized->Initialized
    Botania{r1.2-116} [Botania](Botania r1.2-116.jar) Unloaded->Constructed->Pre-initialized->Initialized
    BuildCraft|Energy{6.0.17} [BC Energy](buildcraft-6.0.17.jar) Unloaded->Constructed->Pre-initialized->Initialized
    eureka{@VERSION@} [Eureka](Eureka-1.7.10-1.2.jar) Unloaded->Constructed->Pre-initialized->Initialized
    bcadditions{1.6.4} [Buildcraft Additions](BuildcraftAdditions-1.7.10-1.6.4.jar) Unloaded->Constructed->Pre-initialized->Initialized
    buildersguides{1.7.10-1.0.0B4} [Builder's Guides](buildersguides-1.7.10-1.0.0B4.jar) Unloaded->Constructed->Pre-initialized->Initialized
    CarpentersBlocks{3.2.8} [Carpenter's Blocks](Carpenter's Blocks v3.2.8 - MC 1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized
    chisel{1.5.7} [Chisel](Chisel-1.7.10-1.5.7.jar) Unloaded->Constructed->Pre-initialized->Initialized
    BuildCraft|Transport{6.0.17} [BC Transport](buildcraft-6.0.17.jar) Unloaded->Constructed->Pre-initialized->Initialized
    ChiselFacades{2.1} [Chisel Facades](ChiselFacades-1.7.10-2.1.jar) Unloaded->Constructed->Pre-initialized->Initialized
    ComputerCraft{1.64pr4} [ComputerCraft](ComputerCraft1.64pr4.jar) Unloaded->Constructed->Pre-initialized->Initialized
    customnpcs{1.7.10b} [CustomNpcs](CustomNPCs_1.7.10b.jar) Unloaded->Constructed->Pre-initialized->Initialized
    props{1.10} [Decocraft](Decocraft-1.10_1.7.2and1.7.10.jar.zip) Unloaded->Constructed->Pre-initialized->Initialized
    dualhotbar{1.6} [Dual Hotbar](dualhotbar-1.7.10-1.6.jar) Unloaded->Constructed->Pre-initialized->Initialized
    eplus{1.7.10-3.0.0a2} [Enchanting Plus](EnchantingPlus-1.7.10-3.0.0a2.jar) Unloaded->Constructed->Pre-initialized->Initialized
    EnderIO{1.7.10-2.1.0_beta.32} [Ender IO](EnderIO-1.7.10-2.1.0_beta.32.jar) Unloaded->Constructed->Pre-initialized->Initialized
    EnderStorage{1.4.5.24} [EnderStorage](EnderStorage-1.7.10-1.4.5.24-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized
    EnderTech{1.7.10-0.3.0.346} [EnderTech](EnderTech-1.7.10-0.3.0.346.jar) Unloaded->Constructed->Pre-initialized->Initialized
    enhancedportals{3.0.6} [EnhancedPortals](EnhancedPortals_1.7.10-universal-3.0.6.jar) Unloaded->Constructed->Pre-initialized->Initialized
    extracells{2.1.12} [ExtraCells](ExtraCells-1.7.10-2.1.12b8.jar) Unloaded->Constructed->Pre-initialized->Initialized
    MetallurgyCore{4.0.3} [Metallurgy Core](MetallurgyCore-1.7.10-4.0.3.11.jar) Unloaded->Constructed->Pre-initialized->Initialized
    TConstruct{1.7.10-1.6.0.build611} [Tinkers' Construct](TConstruct_mc1.7.10_1.6.0d40.1.jar) Unloaded->Constructed->Pre-initialized->Initialized
    Metallurgy{4.0.4} [Metallurgy 4](Metallurgy-1.7.10-4.0.4.43.jar) Unloaded->Constructed->Pre-initialized->Initialized
    ExtraTiC{0.8.4} [ExtraTiC](ExtraTiC-1.7.10-1.0.3.jar) Unloaded->Constructed->Pre-initialized->Initialized
    ForgeMultipart{1.1.0.300} [Forge Multipart](ForgeMultipart-1.7.10-1.1.0.300-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized
    ExtraUtilities{1.1.0k} [Extra Utilities](extrautilities-1.1.0k.jar) Unloaded->Constructed->Pre-initialized->Initialized
    FastCraft{1.9} [FastCraft](fastcraft-1.9.jar) Unloaded->Constructed->Pre-initialized->Initialized
    flansmod{4.7.0} [Flan's Mod](Flans Mod-1.7.10-4.7.0.jar) Unloaded->Constructed->Pre-initialized->Initialized
    Steamcraft{0.26.2} [Flaxbeard's Steam Power](FlaxbeardsSteamPower-1.7.10-0.26.2.jar) Unloaded->Constructed->Pre-initialized->Initialized
    ForgeEssentials{1.3.1-beta1} [Forge Essentials](forgeessentials-1.7.10-1.3.1-beta1.jar) Unloaded->Constructed->Pre-initialized->Initialized
    foxlib{1.7.10-0.5.0} [FoxLib](FoxLib-1.7.10-0.5.0.jar) Unloaded->Constructed->Pre-initialized->Initialized
    GalacticraftCore{3.0.2} [Galacticraft Core](GalacticraftCore-BETA-1.7-3.0.2.199.jar) Unloaded->Constructed->Pre-initialized->Initialized
    GalacticraftMars{3.0.2} [Galacticraft Planets](Galacticraft-Planets-BETA-1.7-3.0.2.199.jar) Unloaded->Constructed->Pre-initialized->Initialized
    GardenCore{1.2.0} [Garden Core](GardenStuff-1.7.10-1.2.1.jar) Unloaded->Constructed->Pre-initialized->Initialized
    GardenContainers{1.2.1} [Garden Containers](GardenStuff-1.7.10-1.2.1.jar) Unloaded->Constructed->Pre-initialized->Initialized
    GardenTrees{1.2.0} [Garden Trees](GardenStuff-1.7.10-1.2.1.jar) Unloaded->Constructed->Pre-initialized->Initialized
    BuildCraft|Silicon{6.0.17} [BC Silicon](buildcraft-6.0.17.jar) Unloaded->Constructed->Pre-initialized->Initialized
    gendustry{1.3.3.25} [GenDustry](gendustry-mc1710-1.3.3.25.jar) Unloaded->Constructed->Pre-initialized->Initialized
    GraveStone{2.9.4} [GraveStone](GraveStone 2.9.4.jar) Unloaded->Constructed->Pre-initialized->Initialized
    HardcoreEnderExpansion{1.6.2} [Hardcore Ender Expansion](HardcoreEnderExpansion  MC-1.7.10  v1.6.2.jar) Unloaded->Constructed->Pre-initialized->Errored
    iChunUtil{4.0.0} [iChunUtil](iChunUtil-4.0.0.jar) Unloaded->Constructed->Pre-initialized->Initialized
    Hats{4.0.0} [Hats](Hats-4.0.0.jar) Unloaded->Constructed->Pre-initialized->Initialized
    ImmibisCore{59.0.3} [Immibis Core](immibis-core-59.0.3.jar) Unloaded->Constructed->Pre-initialized->Initialized
    ImmibisPeripherals{59.0.0} [Immibis's Peripherals](immibis-peripherals-59.0.0.jar) Unloaded->Constructed->Pre-initialized->Initialized
    inventorytweaks{1.59-dev-152-cf6e263} [Inventory Tweaks](InventoryTweaks-1.59-dev-152.jar) Unloaded->Constructed->Pre-initialized->Initialized
    JABBA{1.1.4} [JABBA](Jabba-1.1.4_1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized
    LotsOfFood{1.7.10} [Lots of Food](Lots of Food-1.7.10 v4.jar) Unloaded->Constructed->Pre-initialized->Initialized
    LunatriusCore{1.1.2.14} [LunatriusCore](LunatriusCore-1.7.10-1.1.2.14-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized
    MineFactoryReloaded|CompatAppliedEnergistics{1.7.10R2.8.0RC3} [MFR Compat: Applied Energistics](MineFactoryReloaded-[1.7.10]2.8.0RC3-591.jar) Unloaded->Constructed->Pre-initialized->Initialized
    MineFactoryReloaded|CompatAtum{1.7.10R2.8.0RC2} [MFR Compat: Atum](MineFactoryReloaded-[1.7.10]2.8.0RC3-591.jar) Unloaded->Constructed->Pre-initialized->Initialized
    MineFactoryReloaded|CompatBackTools{1.7.10R2.8.0RC3} [MFR Compat: BackTools](MineFactoryReloaded-[1.7.10]2.8.0RC3-591.jar) Unloaded->Constructed->Pre-initialized->Initialized
    MineFactoryReloaded|CompatBuildCraft{1.7.10R2.8.0RC3} [MFR Compat: BuildCraft](MineFactoryReloaded-[1.7.10]2.8.0RC3-591.jar) Unloaded->Constructed->Pre-initialized->Initialized
    MineFactoryReloaded|CompatChococraft{1.7.10R2.8.0RC2} [MFR Compat: Chococraft](MineFactoryReloaded-[1.7.10]2.8.0RC3-591.jar) Unloaded->Constructed->Pre-initialized->Initialized
    MineFactoryReloaded|CompatExtraBiomes{1.7.10R2.8.0RC2} [MFR Compat: ExtraBiomes](MineFactoryReloaded-[1.7.10]2.8.0RC3-591.jar) Unloaded->Constructed->Pre-initialized->Initialized
    MineFactoryReloaded|CompatForestry{1.7.10R2.8.0RC3} [MFR Compat: Forestry](MineFactoryReloaded-[1.7.10]2.8.0RC3-591.jar) Unloaded->Constructed->Pre-initialized->Initialized
    MineFactoryReloaded|CompatForgeMicroblock{1.7.10R2.8.0RC3} [MFR Compat: ForgeMicroblock](MineFactoryReloaded-[1.7.10]2.8.0RC3-591.jar) Unloaded->Constructed->Pre-initialized->Initialized
    MineFactoryReloaded|CompatIC2{1.7.10R2.8.0RC3} [MFR Compat: IC2](MineFactoryReloaded-[1.7.10]2.8.0RC3-591.jar) Unloaded->Constructed->Pre-initialized->Initialized
    MineFactoryReloaded|CompatMystcraft{1.7.10R2.8.0RC2} [MFR Compat: Mystcraft](MineFactoryReloaded-[1.7.10]2.8.0RC3-591.jar) Unloaded->Constructed->Pre-initialized->Initialized
    MineFactoryReloaded|CompatPams{1.7.10R2.8.0RC2} [MFR Compat: Pam's Mods](MineFactoryReloaded-[1.7.10]2.8.0RC3-591.jar) Unloaded->Constructed->Pre-initialized->Initialized
    ProjRed|Core{4.4.8.47} [ProjectRed](ProjectRed-Base-1.7.10-4.4.8.47.jar) Unloaded->Constructed->Pre-initialized->Initialized
    ProjRed|Exploration{4.4.8.47} [ProjectRed-Exploration](ProjectRed-World-1.7.10-4.4.8.47.jar) Unloaded->Constructed->Pre-initialized->Initialized
    MineFactoryReloaded|CompatProjRed{1.7.10R2.8.0RC2} [MFR Compat ProjectRed](MineFactoryReloaded-[1.7.10]2.8.0RC3-591.jar) Unloaded->Constructed->Pre-initialized->Initialized
    BuildCraft|Builders{6.0.17} [BC Builders](buildcraft-6.0.17.jar) Unloaded->Constructed->Pre-initialized->Initialized
    BuildCraft|Factory{6.0.17} [BC Factory](buildcraft-6.0.17.jar) Unloaded->Constructed->Pre-initialized->Initialized
    Railcraft{9.3.1.0} [Railcraft](Railcraft_1.7.10-9.3.1.0.jar) Unloaded->Constructed->Pre-initialized->Initialized
    MineFactoryReloaded|CompatRailcraft{1.7.10R2.8.0RC3} [MFR Compat: Railcraft](MineFactoryReloaded-[1.7.10]2.8.0RC3-591.jar) Unloaded->Constructed->Pre-initialized->Initialized
    MineFactoryReloaded|CompatRP2{1.7.10R2.8.0RC2} [MFR Compat: RP2](MineFactoryReloaded-[1.7.10]2.8.0RC3-591.jar) Unloaded->Constructed->Pre-initialized->Initialized
    MineFactoryReloaded|CompatSufficientBiomes{1.7.10R2.8.0RC2} [MFR Compat: Sufficient Biomes](MineFactoryReloaded-[1.7.10]2.8.0RC3-591.jar) Unloaded->Constructed->Pre-initialized->Initialized
    MineFactoryReloaded|CompatThaumcraft{1.7.10R2.8.0RC3} [MFR Compat: Thaumcraft](MineFactoryReloaded-[1.7.10]2.8.0RC3-591.jar) Unloaded->Constructed->Pre-initialized->Initialized
    MineFactoryReloaded|CompatThermalExpansion{1.7.10R2.8.0RC3} [MFR Compat: Thermal Expansion](MineFactoryReloaded-[1.7.10]2.8.0RC3-591.jar) Unloaded->Constructed->Pre-initialized->Initialized
    TwilightForest{2.3.1} [The Twilight Forest](twilightforest-1.7.10-2.3.1.jar) Unloaded->Constructed->Pre-initialized->Initialized
    MineFactoryReloaded|CompatTwilightForest{1.7.10R2.8.0RC3} [MFR Compat: TwilightForest](MineFactoryReloaded-[1.7.10]2.8.0RC3-591.jar) Unloaded->Constructed->Pre-initialized->Initialized
    MineFactoryReloaded|CompatVanilla{1.7.10R2.8.0RC3} [MFR Compat: Vanilla](MineFactoryReloaded-[1.7.10]2.8.0RC3-591.jar) Unloaded->Constructed->Pre-initialized->Initialized
    MineTweaker3{${version}} [MineTweaker 3](MineTweaker3-1.7.10-3.0.8B.jar) Unloaded->Constructed->Pre-initialized->Initialized
    ModTweaker{0.5c} [ModTweaker](ModTweaker-1.7.X-0.5d.jar) Unloaded->Constructed->Pre-initialized->Initialized
    ModularForcefieldSystem{3.0-ALPHA-7} [Modular Forcefield System](ModularForcefieldSystem-1.7.10-3.0-ALPHA-7.jar) Unloaded->Constructed->Pre-initialized->Initialized
    Morph{0.9.0} [Morph](Morph-Beta-0.9.0.jar) Unloaded->Constructed->Pre-initialized->Initialized
    Morpheus{1.7.10-1.5.19} [Morpheus](Morpheus-1.7.10-1.5.19.jar) Unloaded->Constructed->Pre-initialized->Initialized
    cfm{3.3.5} [§6MrCrayfish's Furniture Mod](MrCrayfishFurnitureModv3.3.5%281.7.10%29.jar) Unloaded->Constructed->Pre-initialized->Initialized
    NetherOres{1.7.10R2.3.0RC3} [Nether Ores](NetherOres-[1.7.10]2.3.0RC3-84.jar) Unloaded->Constructed->Pre-initialized->Initialized
    NodalMechanics{1.7.10R1.0} [NodalMechanics](NodalMechanics-1.7-1.0-7.jar) Unloaded->Constructed->Pre-initialized->Initialized
    NotEnoughCodecs{0.1} [NotEnoughCodecs](NotEnoughCodecs-0.1.jar) Unloaded->Constructed->Pre-initialized->Initialized
    OpenComponents{0.2.0.20} [OpenComponents](OpenComponents-MC1.7.10-0.2.0.20-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized
    ProjRed|Transmission{4.4.8.47} [ProjectRed-Transmission](ProjectRed-Integration-1.7.10-4.4.8.47.jar) Unloaded->Constructed->Pre-initialized->Initialized
    OpenComputers|Core{1.0.0} [OpenComputers (Core)](OpenComputers-MC1.7.10-1.3.4.63-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized
    OpenComputers{1.3.4.63} [OpenComputers](OpenComputers-MC1.7.10-1.3.4.63-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized
    OpenMods{0.6} [OpenMods](OpenModsLib-1.7.10-0.6-snapshot-223.jar) Unloaded->Constructed->Pre-initialized->Initialized
    MapWriter{2.1.1} [MapWriter](Opis-1.2.3_1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized
    Opis{1.2.3} [Opis](Opis-1.2.3_1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized
    OresPlus{0.7.3.41B} [OresPlus](OresPlus-0.7.3.41B.jar) Unloaded->Constructed->Pre-initialized->Initialized
    harvestcraft{1.7.10b} [Pam's HarvestCraft](Pam's HarvestCraft 1.7.10b.jar) Unloaded->Constructed->Pre-initialized->Initialized
    PneumaticCraft{1.2.6} [PneumaticCraft](PneumaticCraft-1.2.6.jar) Unloaded->Constructed->Pre-initialized->Initialized
    ProjRed|Transportation{4.4.8.47} [ProjectRed-Transportation](ProjectRed-Mechanical_beta-1.7.10-4.4.8.47.jar) Unloaded->Constructed->Pre-initialized->Initialized
    ProjRed|Compatibility{4.4.8.47} [ProjectRed-Compatibility](ProjectRed-Compat-1.7.10-4.4.8.47.jar) Unloaded->Constructed->Pre-initialized->Initialized
    ProjRed|Integration{4.4.8.47} [ProjectRed-Integration](ProjectRed-Integration-1.7.10-4.4.8.47.jar) Unloaded->Constructed->Pre-initialized->Initialized
    ProjRed|Illumination{4.4.8.47} [ProjectRed-Illumination](ProjectRed-Lighting-1.7.10-4.4.8.47.jar) Unloaded->Constructed->Pre-initialized->Initialized
    ProjRed|Expansion{4.4.8.47} [ProjectRed-Expansion](ProjectRed-Mechanical_beta-1.7.10-4.4.8.47.jar) Unloaded->Constructed->Pre-initialized->Initialized
    PvpToggle{0.1.0} [PVP Toggle](pvpToggle-1.7.10-0.1.0-4.jar) Unloaded->Constructed->Pre-initialized->Initialized
    RandomThings{2.1.4} [Random Things](RandomThings-2.1.4.jar) Unloaded->Constructed->Pre-initialized->Initialized
    RedstoneArsenal{1.7.10R1.1.0B4} [Redstone Arsenal](RedstoneArsenal-[1.7.10]1.1.0B4-10.jar) Unloaded->Constructed->Pre-initialized->Initialized
    Roguelike{1.3.5} [Roguelike Dungeons](roguelike-1.7.10-1.3.5.jar) Unloaded->Constructed->Pre-initialized->Initialized
    RouterReborn{1.1.8} [Router Reborn](RouterReborn-1.7.10-1.1.8-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized
    Sanguimancy{1.1.2} [Sanguimancy](Sanguimancy-1.7.10-1.1.2.jar) Unloaded->Constructed->Pre-initialized->Initialized
    simplyjetpacks{1.1.1} [Simply Jetpacks](SimplyJetpacks-MC1.7.10-1.1.1.jar) Unloaded->Constructed->Pre-initialized->Initialized
    SolarFlux{1.7.10-0.4b} [Solar Flux](SolarFlux-1.7.10-0.4b.jar) Unloaded->Constructed->Pre-initialized->Initialized
    Stackie{1.5.1.28} [Stackie](Stackie-1.7.10-1.5.1.28-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized
    statues{2.1.3} [Statues](Statues-Mod-1.7.10.zip) Unloaded->Constructed->Pre-initialized->Initialized
    Sync{4.0.0} [Sync](Sync-4.0.0.jar) Unloaded->Constructed->Pre-initialized->Initialized
    Tails{1.7.10-1.1.1} [Tails](Tails-1.7.10-1.1.1.jar) Unloaded->Constructed->Pre-initialized->Initialized
    thaumicenergistics{0.6.9b} [Thaumic Energistics](thaumicenergistics-0.6.9b.jar) Unloaded->Constructed->Pre-initialized->Initialized
    ThaumicTinkerer{2.5-1.7.10-158} [Thaumic Tinkerer](ThaumicTinkerer-2.5-1.7.10-158.jar) Unloaded->Constructed->Pre-initialized->Initialized
    TiCTooltips{1.1.11b} [TiC Tooltips](TiCTooltips-mc1.7.10-1.1.11b.jar) Unloaded->Constructed->Pre-initialized->Initialized
    TMechworks{1.7.10-75.0afb56c} [Tinkers' Mechworks](TMechworks-1.7.10-0.2.9.jar) Unloaded->Constructed->Pre-initialized->Initialized
    TML{3.0.1} [TooMuchLoot](TooMuchLoot-1.7.10-3.0.1.B22-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized
    Translocator{1.1.1.12} [Translocator](Translocator-1.7.10-1.1.1.12-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized
    WailaHarvestability{1.1.0} [Waila Harvestability](WailaHarvestability-mc1.7.x-1.1.0.jar) Unloaded->Constructed->Pre-initialized->Initialized
    weaponmod{1.7.2 v1.14.2} [Balkon's WeaponMod](weaponmod-1.14.2.jar) Unloaded->Constructed->Pre-initialized->Initialized
    witchery{0.20.5} [Witchery](witchery-1.7.10-0.20.5.jar) Unloaded->Constructed->Pre-initialized->Initialized
    McMultipart{1.1.0.300} [Minecraft Multipart Plugin](ForgeMultipart-1.7.10-1.1.0.300-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized
    IguanaTweaksTConstruct{1.7.10-2.0.5} [Iguana Tinker Tweaks](IguanaTinkerTweaks-1.7.10-2.0.5.jar) Unloaded->Constructed->Pre-initialized->Initialized
    ForgeMicroblock{1.1.0.300} [Forge Microblocks](ForgeMultipart-1.7.10-1.1.0.300-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized
    AE2 Version: beta rv1-beta-37 for Forge 10.13.0.1187
    Mantle Environment: Environment healthy.
    TConstruct Environment: Environment healthy.
    Profiler Position: N/A (disabled)
    Is Modded: Definitely; Server brand changed to 'fml,forge'
    Type: Dedicated Server (map_server.txt)

**Comment by Rakarth802** [comment]
FIXED BECAUSE SKWERL IS A {great person} AND {I volunteered to sit} THROUGH 3 HOURS OF DEBUGGING {to fix this difficult and hard-to-fix issue}.

On a side note, he {was very gracious and kind}, so what {I} put up there in {} are {very true and come from the bottom of my heart}.
